version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 014869289060.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=014869289060.dkr.ecr.us-east-1.amazonaws.com/node-app
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Tagging the Docker image...
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

 post_build:
  commands:
    - echo Build completed on `date`
    - echo Pushing images to ECR
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing image definitions file...
    - DOCKER_CONTAINER_NAME=node-app
    - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
    - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

